name: place_recognition_app
description: A simple place recognition app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  tflite_flutter: ^0.10.4
  image: ^4.0.17
  path_provider: ^2.0.15
  image_picker: ^1.0.4
  supabase_flutter: ^2.8.4
  uuid: ^4.1.0
  video_player: ^2.9.5
  video_thumbnail: ^0.5.3
  path: ^1.8.3
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  flutter_tts: ^4.2.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/models/feature_extractor.tflite